# run_brio_wu.jl — Brio-Wu MHD Shock Tube validation
# Usage: mpirun -np 1 julia run_brio_wu.jl [nsteps]
# Default: 1000 steps
#
# Brio & Wu (1988) standard MHD Riemann problem.
# 1D problem in x-direction, uniform mesh [0, 1], single block.
# γ = 2.0 (required for this test case!)

# ─── Parse CLI ───
const PROFILE_STEPS = length(ARGS) >= 1 ? parse(Int, ARGS[1]) : 1000

# ─── Debug/Runtime flags ───
const debug_nan::Bool = true
const debug_sync::Bool = false
const profiling::Bool = false
const gpu_aware_mpi::Bool = false

const flow_forcing::Bool = false
const forcing_mode::Int64 = 1
const wall_perturbation::Bool = false
const wall_perturbation_type::Int32 = 0
const cache_metrics::Bool = true

# ─── Spectral Warmup ───
const spectral_warmup::Bool = false
const spectral_warmup_order::Int64 = 4

# Precision control
const FT = Float64
const weno_z::Bool = true

# MHD parameters (not used for Brio-Wu, but needed by pipe flow code)
const Re_target::FT = FT(1000.0)
const Ma_target::FT = FT(0.3e0)
const Ro_target::FT = zero(FT)
const Tw::FT = FT(300.0)
const Lx::FT = one(FT)
const hit_forcing_A::FT = zero(FT)

# GPU backend
using CUDA

# ─── Physics / Equation System ───
const equation_type = :MHD
const resistive::Bool = false   # Ideal MHD (no magnetic diffusion)
const cr_glm::FT = FT(0.18e0) # GLM damping ratio

include("physics.jl")
include("solver.jl")

# ─── LES ───
const LES_smag::Bool = false
const LES_wale::Bool = false

# ─── Thermal state ───
# IMPORTANT: Brio-Wu uses γ = 2.0!
const γ::FT = FT(2.0)
const Rg::FT = one(FT)    # Normalized gas constant
const Cp::FT = Rg*γ/(γ-1)
const C_s::FT = zero(FT)   # No Sutherland viscosity needed for inviscid
const T_s::FT = one(FT)
const Pr::FT = 0.71

# ─── Mesh ───
# Single block, 1D in x-direction. Mesh generated by a separate script.
const mesh_dir = "MESH_SMALL"

const _conf_data = h5open(joinpath(mesh_dir, "block_connectivity.h5"), "r") do file
    nblocks = read(file["Nblocks"])
    nx_b = read(file["Nx_b"])
    ny_b = read(file["Ny_b"])
    nz_b = read(file["Nz_b"])
    ng = h5read(joinpath(mesh_dir, "mesh_b0.h5"), "NG")
    (nblocks, Tuple(nx_b), Tuple(ny_b), Tuple(nz_b), Int(ng))
end

const Nblocks::Int64 = _conf_data[1]
const Nx_b::NTuple{Nblocks, Int64} = _conf_data[2]
const Ny_b::NTuple{Nblocks, Int64} = _conf_data[3]
const Nz_b::NTuple{Nblocks, Int64} = _conf_data[4]
const NG::Int64 = _conf_data[5]
const R0::FT = FT(0.5)

const Omega_x::FT = zero(FT)

# ─── GPU Partition ───
const auto_partition_enabled::Bool = true
const gpu_vram_gb::Float64 = 16.0

const Block_Nprocs_manual = [SVector(1,1,1)]

MPI.Init()
include("auto_partition.jl")

const (Block_Nprocs, Block_to_rank) = if auto_partition_enabled
    N_gpus = MPI.Comm_size(MPI.COMM_WORLD)
    if MPI.Comm_rank(MPI.COMM_WORLD) == 0
        println(">>> Auto GPU partition: $N_gpus GPUs, $Nblocks blocks")
    end
    auto_partition(Nx_b, Ny_b, Nz_b, N_gpus;
        NG=NG, Ncons=Ncons, Nprim=Nprim,
        verbose=(MPI.Comm_rank(MPI.COMM_WORLD) == 0),
        gpu_vram_gb=gpu_vram_gb)
else
    (Block_Nprocs_manual, collect(0:length(Block_Nprocs_manual)-1))
end
const Iperiodic = (false, false, false)  # No periodic for shock tube

# ─── Flow control ───
const test_case::String = "BrioWu"
const mesh::String = joinpath(mesh_dir, "mesh_b0.h5")
const metrics::String = joinpath(mesh_dir, "metrics_b0.h5")

const adaptive_dt::Bool = true
const CFL::FT = FT(0.3e0)        # Conservative CFL for MHD
const LTS::Bool = false
const dt::FT = FT(1.0e-4)
const Time::FT = FT(0.1)       # Brio-Wu final time t=0.1
const maxStep::Int64 = profiling ? PROFILE_STEPS : 10000

# ─── Implicit Time Advancement ───
const implicit::Bool = false
const implicit_CFL::FT = FT(10.0)
const implicit_lusgs_sweeps::Int64 = 1
const dual_time::Bool = false
const dual_time_sub_iters::Int64 = 5
const dual_time_tol::FT = FT(1.0e-3)

const plt_xdmf::Bool = true
const plt_out::Bool = true
const step_plt::Int64 = 100

const chk_out::Bool = false
const step_chk::Int64 = 1000
const restart::String = "none"
const inflow_restart::String = "none"

const average::Bool = false
const avg_step::Int64 = 10
const avg_total::Int64 = 1000
const avg_density_weighted::Bool = false

const sample::Bool = false
const sample_step::Int64 = 1000
const sample_index::SVector{3, Int64} = [-1, -1, -1]

# ─── Filtering ───
const filtering::Bool = false       # Inviscid test — no filtering
const filtering_nonlinear::Bool = false
const filtering_interval::Int64 = 10
const filtering_rth::FT = FT(1e-5)
const filtering_s0::FT = FT(0.02e0)

# ─── Equation (Ncons/Nprim defined in physics.jl) ───
const viscous::Bool = false         # Inviscid Brio-Wu
const viscous_order::Int64 = 2
const gg_blend::FT = zero(FT)

# ─── FVM Config ───
const eigen_reconstruction::Bool = false  # Must be false for MHD (no 9×9 eigensystem)
const character::Bool = false
const splitMethodID::Int32 = 1     # 1=Rusanov (safe default for MHD debugging)
const hybrid_ϕ1::FT = FT(0.01e0) # Low threshold: use WENO aggressively for shock tube
const hybrid_ϕ2::FT = one(FT)
const hybrid_ϕ3::FT = FT(10.0)
const Linear_ϕ::FT = one(FT)   # Pure upwind (no KEP blend for shock tube)
const UP7::SVector{7, FT} = SVector(-3/420, 25/420, -101/420, 319/420, 214/420, -38/420, 4/420)
const CD6::SVector{7, FT} = SVector(0, 1/60, -2/15, 37/60, 37/60, -2/15, 1/60)
const Linear::SVector{7, FT} = UP7 * Linear_ϕ + CD6 * (one(FT) - Linear_ϕ)
const ΔLinear::SVector{7, FT} = UP7 - CD6

# GPU Kernel Config
const maxreg::Int64 = 256
const nthreads::Tuple{Int32, Int32, Int32} = (8, 4, 8)
const nthreads2::Tuple{Int32, Int32, Int32} = (16, 8, 8)

# ═════════════════════════════════════════════════════════
#                  ENTRY POINT
# ═════════════════════════════════════════════════════════

comm = MPI.COMM_WORLD
rank = MPI.Comm_rank(comm)

if rank == 0
    println("=" ^ 70)
    println("  Flame3D — Brio-Wu MHD Shock Tube Validation")
    println("=" ^ 70)
    print_gpu_backend_info()
    println("  Equation:   MHD (Ncons=$Ncons, Nprim=$Nprim)")
    println("  γ:          $γ")
    println("  GLM cr:     $cr_glm")
    println("  Solver:     Rusanov (splitMethodID=$splitMethodID)")
    println("  Test case:  ", test_case)
    println("  Blocks:     ", Nblocks)
    println("  Steps:      ", maxStep)
    println("  Final time: ", Time)
    println("=" ^ 70)
    println()
end

warmup_start = time_ns()
time_step(rank, comm, Block_Nprocs)
warmup_time = (time_ns() - warmup_start) / 1e9

if rank == 0
    println()
    println("=" ^ 70)
    println("  BRIO-WU COMPLETE")
    println("=" ^ 70)
    @printf("  Total wall time:     %.3f s\n", warmup_time)
    @printf("  Steps completed:     %d\n",     maxStep)
    @printf("  Time per step:       %.4f s\n", warmup_time / maxStep)
    println("=" ^ 70)
    flush(stdout)
end

MPI.Finalize()
